### ISSUE TITLE
Cannot find module '@angular/common/http' from '../../node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs'

### ISSUE THREAD

**Issue by sanjay-dandekar-jktech** [cipchk/ngx-filesaver#53]
We have an Angular app that I recently upgraded to Angular 15 (from Angular 11). After upgrading - running the unit test case we get the following error:

```
    Cannot find module '@angular/common/http' from '../../node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs'

    Require stack:
      /<<path>>/node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs
      src/app/utils/utils-service.ts
      src/app/utils/index.ts
      src/app/services/actions-listener.service.ts
      src/app/services/index.ts
```

ng version output:

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.2.10
Node: 18.18.0
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1502.10
@angular-devkit/build-angular      15.2.10
@angular-devkit/core               15.2.10
@angular-devkit/schematics         15.2.10
@angular/cdk                       15.2.9
@angular/material                  15.2.9
@angular/material-moment-adapter   15.2.9
@schematics/angular                15.2.10
rxjs                               6.5.5
typescript                         4.9.5
```

Package json has following version of ngx-filesaver:

"ngx-filesaver": "15.0.0",

The Angular project is part of a mono repo. The node_modules in the root folder does not contain the @angular/common but the node_modules of the Angular app does contain the @angular/common folder.

Any pointers on what could be wrong?

I also tried importing HttpClientModule and the FileSaverModule in my main app module but it did not help. It was not required in Angular version 11.

**Comment by cipchk** [comment]
Most of these errors are caused by the existence of multiple copies of `@angular/common`, you can try to delete `node_modules` and install the dependencies again.

**Comment by sanjay-dandekar-jktech** [comment]
I have checked multiple times - There is just one common module and its version is 15.2.10. I also tried cleanup - multiple times but it has not helped.

**Comment by cipchk** [comment]
Is it possible to locate `../../node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs` in the `src/app/utils/utils-service.ts` file?

**Comment by sanjay-dandekar-jktech** [comment]
This import line in `utils-service.ts` results in loading of `../../node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs`

`import { FileSaverService } from 'ngx-filesaver';`

The full error stack is as follows:

```
    Cannot find module '@angular/common/http' from '../../node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs'

    Require stack:
      /<<path>>/node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs
      src/app/utils/utils-service.ts
      src/app/utils/index.ts
      src/app/services/actions-listener.service.ts
      src/app/services/index.ts
      src/app/+shared/components/transaction-confirmation-dialog/transaction-confirmation-dialog.component.ts
      src/app/+shared/components/index.ts
      src/app/+platform-admin/+workflow-templates/components/configure-workflow-template/configure-workflow-template.component.test.ts

      1 | import { Injectable } from '@angular/core';
      2 | import moment from 'moment';
    > 3 | import { FileSaverService } from 'ngx-filesaver';
        | ^
      4 | import { orderBy } from 'lodash';
      5 |
      6 | import { UserInterface } from '@events';

      at Resolver._throwModNotFoundError (../../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (../../node_modules/ngx-filesaver/fesm2020/ngx-filesaver.mjs:4:21)
      at Object.<anonymous> (src/app/utils/utils-service.ts:3:1)
      at Object.<anonymous> (src/app/utils/index.ts:4:1)
      at Object.<anonymous> (src/app/services/actions-listener.service.ts:9:1)
      at Object.<anonymous> (src/app/services/index.ts:2:1)
      at Object.<anonymous> (src/app/+shared/components/transaction-confirmation-dialog/transaction-confirmation-dialog.component.ts:8:1)
      at Object.<anonymous> (src/app/+shared/components/index.ts:2:1)
      at Object.<anonymous> (src/app/+platform-admin/+workflow-templates/components/configure-workflow-template/configure-workflow-template.component.test.ts:18:1)
```

PS: This was a working code in Angular 11.

**Comment by cipchk** [comment]
In fact, there are no changes from version `9` to now. I still think it may be caused by incorrect installation of dependencies.

**Comment by sanjay-dandekar-jktech** [comment]
Found out the issue - Seems like something is wrong with hoisting in the monorepo. Hence the @angular/common (eventhough exact same version is used in all 1 frontend projects) is not getting hoisted to the root node_modules. For now I forced install in the root node_modules by adding it in the main package.json and the error is gone.
